### ISSUE TITLE
Improve containerization of the backend server

### ISSUE THREAD

**Issue by bartekpacia** [kacaleksandra/notes#11]
There are several problems with out current Dockerfile:

1. it uses `npm` to run the Node.js app, [which is an antipattern](https://github.com/Yelp/dumb-init). We should run directly with `node` instead, or even better, use `dumb-init`.

1. shutting down containers (`docker compose down`) takes too much time (usually ~10 seconds). (This is probably related to our usage of `npm`.

1. `docker compose up` is flaky. I don't have any reproduction information, unfortunately, but I quite often have to run `docker compose up` twice because it fails for the first time with <strange errors>.

1. We don't verify that Docker works on CI. We could really use a simple integration test that is running in [the main-backend job](https://github.com/kacaleksandra/notes/blob/586e20e45ff69bbd7098fff327d277c01806c70c/.github/workflows/prepare.yaml#L31). This would make it easier to avoid such errors in the future.

We could create a Bash script like this (pseudocode):
```
#!/usr/bin/env bash
set -euo pipefail

docker compose up
# 1. wait until app is ready
# 2. create user
# 3. log in user
```

If exit code is non-zero, we fail the workflow and merging is blocked.

**Comment by P3T3R3** [comment]
dumb-init and minor configuration changes seems to solve 1-3 problems, will be merged here:
https://github.com/kacaleksandra/notes/pull/13
